[{$smarty.block.parent}]
[{if $oViewConf->getActiveTheme() == 'azure'}]
    [{oxstyle include=$oViewConf->getModuleUrl('oedsgvobase','out/css/oedsgvobase-azure.css')}]
[{else}]
    [{oxstyle include=$oViewConf->getModuleUrl('oedsgvobase','out/css/oedsgvobase-flow.css')}]
[{/if}]
