[{$smarty.block.parent}]
[{if $oView->oeDsgvoBaseIsUserAllowedToDeleteOwnAccount()}]
    [{if $oViewConf->getActiveTheme() == 'azure'}]
        [{include file="oedsgvobasedashboard_azure.tpl"}]
    [{elseif $oViewConf->getActiveTheme() == 'flow'}]
        [{include file="oedsgvobasedashboard_flow.tpl"}]
    [{else}]
        [{block name="oedsgvobase_account_delete_my_account"}]
        [{* Overwrite this block, if the above does not fit, because you are using a different theme *}]
        [{/block}]
    [{/if}]
[{/if}]
