[{$smarty.block.parent}]
[{if $oView->oeGdprBaseIsUserAllowedToDeleteOwnAccount()}]
    [{if $oViewConf->getActiveTheme() == 'azure'}]
        [{include file="oegdprbasedashboard_azure.tpl"}]
    [{elseif $oViewConf->getActiveTheme() == 'flow'}]
        [{include file="oegdprbasedashboard_flow.tpl"}]
    [{else}]
        [{block name="oegdprbase_account_delete_my_account"}]
        [{* Overwrite this block, if the above does not fit, because you are using a different theme *}]
        [{/block}]
    [{/if}]
[{/if}]
